# Generated by Django 5.1.2 on 2024-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="TimeEnd",
            field=models.CharField(
                choices=[
                    ("09:40", "9:40 AM"),
                    ("10:30", "10:30 AM"),
                    ("11:20", "11:20 AM"),
                    ("11:30", "11:30 AM"),
                    ("12:20", "12:20 PM"),
                    ("13:10", "1:10 PM"),
                    ("14:00", "2:00 PM"),
                    ("14:50", "2:50 PM"),
                    ("15:40", "3:40 PM"),
                    ("16:30", "4:30 PM"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="Timestart",
            field=models.CharField(
                choices=[
                    ("09:40", "9:40 AM"),
                    ("10:30", "10:30 AM"),
                    ("11:20", "11:20 AM"),
                    ("11:30", "11:30 AM"),
                    ("12:20", "12:20 PM"),
                    ("13:10", "1:10 PM"),
                    ("14:00", "2:00 PM"),
                    ("14:50", "2:50 PM"),
                    ("15:40", "3:40 PM"),
                    ("16:30", "4:30 PM"),
                ],
                max_length=5,
            ),
        ),
    ]
