# Generated by Django 5.1.2 on 2024-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_timetable_timeend_alter_timetable_timestart"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("Teacher", "Day", "Section", "RegisteredDate"),
                name="unique_teacher_day_section_registration",
            ),
        ),
    ]
