# Generated by Django 5.1.2 on 2024-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_timetable_unique_teacher_day_section_registration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetable",
            name="unique_teacher_day_section_registration",
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("Teacher", "Day", "Section"),
                name="unique_teacher_day_section_registration",
            ),
        ),
    ]
