# Generated by Django 5.1.2 on 2024-10-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0004_remove_timetable_unique_teacher_day_section_registration_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetable",
            name="unique_teacher_day_section_registration",
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("Day", "Timestart", "Section"),
                name="unique_time_slot_day_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("Teacher", "Day", "Section", "RegisteredDate"),
                name="unique_teacher_day_section_registration",
            ),
        ),
    ]
