# Generated by Django 5.1.2 on 2024-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0005_remove_timetable_unique_teacher_day_section_registration_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.UniqueConstraint(
                fields=("Venue", "Day", "Timestart"), name="unique_venue_day_time"
            ),
        ),
    ]
