# Generated by Django 5.1.2 on 2024-11-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_timetable_unique_venue_day_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetable",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="timetable",
            name="unique_time_slot_day_section",
        ),
        migrations.RemoveConstraint(
            model_name="timetable",
            name="unique_teacher_day_section_registration",
        ),
        migrations.RemoveConstraint(
            model_name="timetable",
            name="unique_venue_day_time",
        ),
    ]
