# Generated by Django 5.1.2 on 2024-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_timetable_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="Section",
            field=models.CharField(
                choices=[
                    ("A1", "A1"),
                    ("B1", "B2"),
                    ("C1", "C2"),
                    ("D1", "D2"),
                    ("A2", "A2"),
                    ("B2", "B2"),
                    ("C2", "C2"),
                    ("D2", "D2"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                ],
                default=None,
                max_length=2,
            ),
        ),
    ]
