# Generated by Django 5.1.2 on 2024-11-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_timetable_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="SessionType",
            field=models.CharField(
                choices=[
                    ("Tutorial", "Tutorial"),
                    ("Lecture", "Lecture"),
                    ("Lab", "Lab"),
                    ("Add_On", "Add_On"),
                    ("Minor_Project", "Minor_Project"),
                    ("internship", "Internship"),
                ],
                max_length=20,
            ),
        ),
    ]
