# Generated by Django 5.1.2 on 2024-11-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_timetable_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetable",
            name="unique_teacher_venue_timestart_day_section",
        ),
    ]
